# Generated by Django 5.0.2 on 2024-02-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_product_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
