# Generated by Django 5.0.2 on 2024-04-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_method_control_sum_of_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='methods',
            field=models.ManyToManyField(to='products.method'),
        ),
    ]
