# Generated by Django 5.0.2 on 2024-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_rename_max_item_setting_max_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='aux_params',
            field=models.ManyToManyField(to='products.methodparam'),
        ),
    ]
