# Generated by Django 5.0.2 on 2024-04-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_methodparam_method_aux_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodparam',
            name='description',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
