# Generated by Django 5.0.2 on 2024-05-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_criterion_name_short_item_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='need_criterion_weight',
            field=models.BooleanField(default=False),
        ),
    ]
