# Generated by Django 5.0.2 on 2024-05-05 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_task_aux_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('param', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param', to='products.methodparam')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.task')),
            ],
        ),
    ]
