# Generated by Django 5.0.2 on 2024-05-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auxparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param', to='products.methodparam'),
        ),
        migrations.AddField(
            model_name='task',
            name='value',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AuxParam',
        ),
    ]
