# Generated by Django 5.0.2 on 2024-05-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_remove_task_param_remove_task_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='aux_params',
            new_name='params',
        ),
    ]
