# Generated by Django 5.0.2 on 2024-05-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_method_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='description',
        ),
    ]
