# Generated by Django 5.0.2 on 2024-05-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_param_single_alter_method_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='single',
            field=models.BooleanField(default=True),
        ),
    ]
