# Generated by Django 5.0.2 on 2024-05-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_remove_paramaux_criterion_alter_paramaux_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='cellparam',
            name='criterion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.criterion'),
        ),
    ]
