# Generated by Django 5.0.2 on 2024-05-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_criterion_direction_method_need_criterion_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='need_decart',
            field=models.BooleanField(default=False),
        ),
    ]
