# Generated by Django 5.0.2 on 2024-05-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_rename_need_decart_method_need_descartes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celldescartes',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
