# Generated by Django 5.0.2 on 2024-05-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_rename_celld_celldescartescriterion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='need_descartes',
            new_name='need_descartes_criterion',
        ),
    ]
