# Generated by Django 5.0.2 on 2024-05-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_rename_need_descartes_method_need_descartes_criterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celldescartescriterion',
            name='changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celldescartesitem',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
