# Generated by Django 4.2.13 on 2024-05-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_criterion_direction_bool_alter_criterion_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
