# Generated by Django 4.2.13 on 2024-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_task_use_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='normalize_param_k',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterion',
            name='normalize_param_p',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='enable_normalization',
            field=models.BooleanField(default=False),
        ),
    ]
