# Generated by Django 4.2.10 on 2024-11-04 21:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0077_method_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
