# Generated by Django 5.0.2 on 2024-02-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_variant_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product',
            new_name='task',
        ),
    ]
