# Generated by Django 5.0.2 on 2024-04-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_method_remove_choice_votes_choice_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='methods',
            field=models.ManyToManyField(blank=True, null=True, to='products.method'),
        ),
    ]
