# Generated by Django 5.0.2 on 2024-04-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
