# Generated by Django 5.0.2 on 2024-04-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_choice_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Condition',
            new_name='Criterion',
        ),
        migrations.RenameField(
            model_name='cell',
            old_name='condition',
            new_name='criterion',
        ),
        migrations.AlterField(
            model_name='choice',
            name='methods',
            field=models.ManyToManyField(blank=True, to='products.method'),
        ),
    ]
