# Generated by Django 5.0.2 on 2024-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_method_description_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_item', models.IntegerField(default=4)),
                ('max_criterions', models.IntegerField(default=4)),
            ],
        ),
        migrations.AlterField(
            model_name='method',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
