# Generated by Django 5.0.2 on 2024-05-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_method_aux_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='aux_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
