# Generated by Django 5.0.2 on 2024-05-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_task_param_task_value_delete_auxparam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MethodParam',
            new_name='Param',
        ),
    ]
