# Generated by Django 5.0.2 on 2024-05-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_paramaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='param',
        ),
        migrations.RemoveField(
            model_name='task',
            name='value',
        ),
    ]
