# Generated by Django 5.0.2 on 2024-05-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_result_item_alter_result_method_and_more'),
    ]

    operations = [
    ]
