# Generated by Django 5.0.2 on 2024-05-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
