# Generated by Django 5.0.2 on 2024-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_delete_image_alter_cellparam_criterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellparam',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
