# Generated by Django 5.0.2 on 2024-05-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_alter_cellparam_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='direction',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='need_criterion_direction',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CellParam',
        ),
    ]
