# Generated by Django 5.0.2 on 2024-05-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_method_need_decart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='need_decart',
            new_name='need_descartes',
        ),
        migrations.CreateModel(
            name='CellDescartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('id_i', models.IntegerField()),
                ('id_j', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.task')),
            ],
        ),
    ]
