# Generated by Django 5.0.2 on 2024-05-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_celldescartes_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CellDescartes',
            new_name='CellD',
        ),
    ]
