# Generated by Django 5.0.2 on 2024-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_rename_celldescartes_celld'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='need_descartes_item',
            field=models.BooleanField(default=False),
        ),
    ]
