# Generated by Django 5.0.2 on 2024-05-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_method_need_descartes_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellDescartesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_i', models.IntegerField()),
                ('id_j', models.IntegerField()),
                ('value', models.FloatField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.criterion')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.task')),
            ],
        ),
    ]
