# Generated by Django 5.0.2 on 2024-05-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_celldescartesitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CellD',
            new_name='CellDescartesCriterion',
        ),
    ]
