# Generated by Django 4.2.13 on 2024-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_alter_criterion_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='direction_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='direction',
            field=models.IntegerField(),
        ),
    ]
