# Generated by Django 4.2.13 on 2024-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_criterion_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramaux',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
