# Generated by Django 4.2.13 on 2024-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_paramaux_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
