# Generated by Django 4.2.13 on 2024-05-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_criterion_normalize_param_k_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='direction',
        ),
    ]
