# Generated by Django 4.2.13 on 2024-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_remove_criterion_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='normalize_param_k',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='normalize_param_p',
            field=models.FloatField(default=0),
        ),
    ]
