# Generated by Django 5.0.2 on 2024-07-20 20:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_alter_criterion_normalize_param_k_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
